let routeFilenames = [];

module.exports = (router, app) => {

  // resource apis - appended automatically by CLI to the bottom of this file
  routeFilenames.forEach(filename => {
    console.log("loading api: " + filename);
    require('../../resources/' + filename)(router);
  });

  // catch all other api requests and send 404
  router.all('/api/*', (req, res) => {
    res.send(404);
  });
}

// New Yote resource API route names generated by the Yote CLI
routeFilenames.push('user/userApi');
routeFilenames.push('product/productApi');